### ISSUE TITLE
Auto create output directory?

### ISSUE THREAD

**Issue by hija** [chk1/stw2openmensa#6]
I think, the output directory should be automatically created if it does not exist yet since this would make the project a little bit simpler to use. Is there a reason this has not been implemented? 

Otherwise, I could do it :)

**Comment by chk1** [comment]
No there's no specific reason for this, would be a good feature though
Can you implement it?

**Comment by hija** [comment]
I just did a pull request: https://github.com/chk1/stw2openmensa/pull/7
